version: '3.7'
services:

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: nextjs-mui-kit
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nextjs-mui-kit-secret

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

